import type { Metadata } from "next";
import Link from "next/link";
import { BRAND } from "@/config/site";

export const metadata: Metadata = { robots: { index: false, follow: false } };

export default function Bases() {
  return <Legal title="Bases legales — versión de trabajo"><Notice /><h2>1. Organizador</h2><p>Completar razón social, RUC, domicilio y datos de contacto del organizador antes de abrir ventas.</p><h2>2. Dinámica</h2><p>YaTeToca Auto Nuevo contempla 3,000 oportunidades numeradas. Cada ticket cuesta S/50. Los packs disponibles son 1 por S/50, 3 por S/150 y 5 por S/250. El límite máximo es de 5 tickets por persona.</p><h2>3. Premios</h2><p>Habrá seis ganadores distintos: una Changan X7 Plus 2027, un iPhone 17 Pro, un viaje a Cusco para dos personas con hospedaje y cuatro premios de S/200.</p><h2>4. Sorteo</h2><p>El orden previsto es cuatro premios de S/200, viaje a Cusco, iPhone 17 Pro y Changan X7 Plus como gran final. El sorteo se transmitirá en vivo por Instagram. La fecha, método verificable y condiciones definitivas deben publicarse antes de cobrar.</p><h2>5. Entrega</h2><p>Los premios se entregarán en Lima, previa validación de identidad. El viaje tendrá fechas elegidas por el ganador dentro de las condiciones de la reserva.</p><h2>6. Pagos y devoluciones</h2><p>Una solicitud queda pendiente hasta validar el pago. Las condiciones de cancelación, devolución y el tratamiento si no se completan los cupos deben quedar definidas en la versión final.</p><h2>7. Privacidad y reclamos</h2><p>Los datos se usarán para validar pagos, asignar números, contactar participantes y cumplir obligaciones legales. Incorporar responsable del banco de datos y Libro de Reclamaciones.</p><p className="muted mt-10 text-sm">Versión técnica: {BRAND.legalVersion}</p></Legal>;
}
function Notice() { return <div className="mb-8 rounded-2xl border border-amber-400/30 bg-amber-400/10 p-5 text-amber-100"><b>No publicar ni aceptar pagos con este texto.</b><p className="mt-2 text-sm">Debe ser revisado por un abogado y completado con las autorizaciones y condiciones oficiales del sorteo.</p></div>; }
function Legal({ title, children }: { title: string; children: React.ReactNode }) { return <main className="shell py-16"><Link href="/" className="text-blue-300">← Volver</Link><article className="prose prose-invert mt-10 max-w-3xl [&_h1]:font-[var(--font-display)] [&_h1]:text-4xl [&_h2]:mt-10 [&_h2]:font-[var(--font-display)] [&_h2]:text-2xl [&_p]:leading-7 [&_p]:text-slate-300"><h1>{title}</h1>{children}</article></main>; }
