"use client";
import { useState } from "react";
import { Analytics,track } from "@/components/analytics";
import { Arrow,Check,Shield } from "@/components/icons";
import { MyTickets } from "@/components/my-tickets";
import { PhoneVisual } from "@/components/phone-visual";
import { PurchaseFlow } from "@/components/purchase-flow";
import { TicketBrowser } from "@/components/ticket-browser";
import { BRAND,PACKS,type PackId } from "@/config/site";
import { money,percent } from "@/lib/format";
import type { Raffle } from "@/lib/types";

const faqs=[
 ["¿Cuántas oportunidades existen?","Este sorteo tiene exactamente 1,000 oportunidades numeradas. La cantidad no cambia después de publicarse las bases."],
 ["¿Cuándo se realiza el sorteo?","Cuando se complete el total de oportunidades o según la condición y fecha informadas en las bases legales."],
 ["¿Cómo se elige al ganador?","El mecanismo definitivo se publicará en las bases antes de abrir ventas y deberá permitir verificar el resultado públicamente."],
 ["¿Cómo sé qué números tengo?","Después de validar el pago recibirás tus números. También podrás consultarlos con tu celular, DNI o código de compra."],
 ["¿Qué pasa si mi pago no se valida?","La orden quedará pendiente mientras se revisa. Si el pago no aparece o los datos no coinciden, se rechazará sin asignar números."],
 ["¿Puedo comprar más oportunidades?","Sí, mientras existan cupos y la participación cumpla las condiciones de las bases."],
 ["¿Puedo transferir mi número?","Solo si las bases definitivas lo permiten y se completa el procedimiento de identificación correspondiente."],
 ["¿Cómo se entrega el premio?","Se valida la identidad del ganador y se documenta la entrega dentro del plazo indicado para el premio."],
 ["¿Dónde puedo ver las bases legales?","En el enlace Bases legales, disponible antes de confirmar cualquier pago."],
];

export function Landing({raffle}:{raffle:Raffle}){
 const[selected,setSelected]=useState<PackId|null>(null); const available=Math.max(raffle.totalSlots-raffle.soldSlots,0); const progress=Math.min(100,(raffle.soldSlots/raffle.totalSlots)*100);
 const choose=(id:PackId)=>{const pack=PACKS.find(item=>item.id===id);if(!pack||pack.quantity>available)return;setSelected(id);track("select_pack",{pack:id})};
 return <><Analytics/><header className="absolute inset-x-0 top-0 z-20"><div className="shell flex h-20 items-center justify-between"><a href="#inicio" className="display text-sm font-bold tracking-tight"><span className="mr-2 inline-block h-3 w-3 rotate-45 bg-[#b8ff3d]"/>{BRAND.provisionalName}</a><nav className="hidden items-center gap-6 text-sm text-slate-300 md:flex"><a href="#como-funciona">Cómo funciona</a><a href="#transparencia">Transparencia</a><MyTickets total={raffle.totalSlots}/></nav><a href="#packs" className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold md:hidden">Participar</a></div></header>
 <main id="inicio"><section className="grid-noise relative overflow-hidden border-b border-white/8 pb-20 pt-28 sm:pb-28 sm:pt-36"><div className="absolute left-1/2 top-0 h-[500px] w-[800px] -translate-x-1/2 bg-[radial-gradient(circle,rgba(40,120,255,.18),transparent_62%)]"/><div className="shell relative grid items-center gap-16 lg:grid-cols-[1.15fr_.85fr]"><div><div className="mb-7 flex flex-wrap items-center gap-3"><span className="rounded-full border border-blue-400/30 bg-blue-500/10 px-3 py-1.5 text-xs font-bold text-blue-200">Cupos limitados y visibles</span>{raffle.demo&&<span className="rounded-full border border-amber-400/30 bg-amber-400/10 px-3 py-1.5 text-xs font-bold text-amber-200">Modo demo · no realizar pagos</span>}</div><h1 className="display max-w-3xl text-[clamp(3rem,8vw,6.7rem)] font-bold leading-[.91] tracking-[-.06em]">¿Hace cuánto participas y nunca ganas?</h1><p className="muted mt-7 max-w-2xl text-base leading-7 sm:text-xl">Queremos hacerlo diferente: cupos limitados, oportunidades visibles y un sorteo totalmente transparente.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row">{available>0?<a href="#packs" className="button-primary gap-2" onClick={()=>track("view_content",{section:"packs"})}>Quiero participar <Arrow/></a>:<span className="button-secondary cursor-not-allowed opacity-70">Cupos completos</span>}<MyTickets total={raffle.totalSlots}/></div><div className="mt-10 max-w-2xl"><div className="mb-3 flex items-end justify-between gap-4"><div><span className="muted text-xs">Oportunidades vendidas</span><p className="display text-4xl font-bold sm:text-6xl">{raffle.soldSlots.toLocaleString("es-PE")} <span className="text-slate-600">/ {raffle.totalSlots.toLocaleString("es-PE")}</span></p></div><span className="text-right text-sm font-extrabold text-[#b8ff3d]">{available.toLocaleString("es-PE")} disponibles</span></div><div className="h-3 overflow-hidden rounded-full bg-white/8" role="progressbar" aria-label="Oportunidades vendidas" aria-valuemin={0} aria-valuemax={raffle.totalSlots} aria-valuenow={raffle.soldSlots}><div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-[#b8ff3d]" style={{width:`${progress}%`}}/></div><p className="muted mt-3 text-xs">Se actualiza únicamente con pagos validados.</p></div></div><PhoneVisual images={raffle.prizeImages}/></div></section>

 <section className="section border-b border-white/8" id="premio"><div className="shell grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold text-blue-300">Premio principal</p><h2 className="display mt-3 text-5xl font-bold tracking-tight sm:text-7xl">{raffle.name}</h2><p className="muted mt-6 max-w-xl text-lg leading-8">{raffle.description}</p></div><div className="card rounded-[30px] p-6 sm:p-9"><div className="flex items-start justify-between border-b border-white/10 pb-6"><span className="muted">Valor aproximado</span><b className="display text-3xl">{money(raffle.approximateValue)}</b></div><ul className="grid gap-4 py-7 sm:grid-cols-2">{raffle.features.map(item=><li key={item} className="flex gap-3 text-sm text-slate-200"><Check className="h-5 w-5 shrink-0 text-[#b8ff3d]"/>{item}</li>)}</ul><div className="grid gap-4 border-t border-white/10 pt-6 text-sm sm:grid-cols-2"><p><span className="muted block">Estado</span><b>Nuevo</b></p><p><span className="muted block">Entrega estimada</span><b>{raffle.estimatedDelivery}</b></p></div></div></div></section>

 <section className="border-b border-white/8 bg-[#050914] py-8"><div className="shell grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-3"><Stat label="Oportunidades disponibles" value={available.toLocaleString("es-PE")} lime/><Stat label="Números vendidos" value={raffle.soldSlots.toLocaleString("es-PE")}/><Stat label="Fecha estimada del sorteo" value={raffle.drawLabel}/></div><p className="muted shell mt-4 text-sm">El sorteo se realizará cuando se complete el total de oportunidades o según lo indicado en las bases.</p></section>

 <section className="section bg-[#071020]" id="packs"><div className="shell"><div className="max-w-2xl"><h2 className="display text-4xl font-bold tracking-tight sm:text-6xl">Elige cuántas oportunidades quieres ver a tu nombre.</h2><p className="muted mt-5 text-lg">Sabes exactamente contra cuántas oportunidades participas. Menos incertidumbre. Más claridad.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{PACKS.map((pack,index)=>{const disabled=pack.quantity>available;return <button key={pack.id} disabled={disabled} onClick={()=>choose(pack.id)} className={`group relative overflow-hidden rounded-[28px] border p-7 text-left transition-transform enabled:hover:-translate-y-1 disabled:cursor-not-allowed disabled:opacity-45 ${index===1?"border-blue-400 bg-blue-500/12 glow":"border-white/12 bg-[#0b1428]"}`}><div className="flex min-h-7 justify-between">{pack.badge?<span className={`rounded-full px-3 py-1 text-xs font-black ${index===1?"bg-blue-500 text-white":"bg-[#b8ff3d] text-[#071009]"}`}>{pack.badge}</span>:<span/>}<Arrow className="text-slate-500 group-hover:text-white"/></div><p className="display mt-10 text-5xl font-bold">{pack.quantity}</p><p className="muted">{pack.quantity===1?"oportunidad":"oportunidades"}</p><p className="display mt-8 text-4xl font-bold text-[#b8ff3d]">{money(pack.price)}</p><div className="mt-6 border-t border-white/10 pt-5 text-sm"><p>Tendrías <b>{pack.quantity} de {raffle.totalSlots.toLocaleString("es-PE")}</b></p><p className="muted mt-1"><b className="text-white">{pack.quantity} / {raffle.totalSlots.toLocaleString("es-PE")}</b> · Probabilidad aproximada: <b className="text-white">{percent(pack.quantity,raffle.totalSlots)}</b></p>{disabled&&<p className="mt-2 text-amber-200">No quedan suficientes cupos para este pack.</p>}</div></button>})}</div><p className="muted mt-5 max-w-3xl text-xs leading-5">La probabilidad es una relación matemática entre oportunidades adquiridas y oportunidades totales. No garantiza un resultado ganador.</p></div></section>

 <section className="section" id="como-funciona"><div className="shell"><h2 className="display text-4xl font-bold sm:text-6xl">Cuatro pasos. Sin zonas grises.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-[28px] border border-white/10 bg-white/10 md:grid-cols-4">{[["Elige tus oportunidades","Compara los packs y revisa la probabilidad."],["Paga mediante Yape","Usa el QR y conserva tu operación."],["Confirmamos tu pago","Una persona revisa el abono antes de aprobarlo."],["Recibe tus números","Se asignan automáticamente, sin duplicados."]].map((step,i)=><article key={step[0]} className="bg-[#081020] p-7"><span className="display text-5xl font-bold text-blue-500/35">0{i+1}</span><h3 className="display mt-12 text-xl font-bold">{step[0]}</h3><p className="muted mt-3 text-sm leading-6">{step[1]}</p></article>)}</div></div></section>

 <section className="section border-y border-white/8 bg-[#071020]" id="transparencia"><div className="shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><Shield className="h-10 w-10 text-[#b8ff3d]"/><h2 className="display mt-6 text-5xl font-bold tracking-tight">Queremos que puedas ver todo.</h2><p className="muted mt-5 leading-7">Cada cifra tiene una explicación. Los datos personales permanecen privados.</p><div className="mt-7 flex flex-wrap gap-3"><a className="button-secondary" href="/bases">Ver bases legales</a><TicketBrowser total={raffle.totalSlots}/><span className="button-secondary cursor-not-allowed opacity-50" aria-disabled="true">Ver ganador · pendiente</span></div></div><div className="grid gap-3 sm:grid-cols-2"><Stat label="Total de oportunidades" value={raffle.totalSlots.toLocaleString("es-PE")}/><Stat label="Vendidas" value={raffle.soldSlots.toLocaleString("es-PE")}/><Stat label="Disponibles" value={available.toLocaleString("es-PE")} lime/><Stat label="Fecha del sorteo" value={raffle.drawLabel}/><Info title="Cómo se elige al ganador">El método verificable se detalla en las bases definitivas.</Info><Info title="Cómo se valida y entrega">Se publica el resultado, se valida la identidad y se documenta la entrega.</Info></div></div></section>

 <section className="section"><div className="shell grid gap-12 lg:grid-cols-2"><div><h2 className="display text-4xl font-bold sm:text-6xl">Preguntas claras. Respuestas directas.</h2><p className="muted mt-5 max-w-md">Si una regla cambia, primero se actualizarán las bases y la información visible del sorteo.</p></div><div className="divide-y divide-white/10 border-y border-white/10">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold"><span>{q}</span><span className="text-blue-400 group-open:rotate-45">＋</span></summary><p className="muted max-w-xl pt-3 text-sm leading-6">{a}</p></details>)}</div></div></section>

 <section className="overflow-hidden bg-[#2878ff] py-20 text-white"><div className="shell relative"><p className="display max-w-4xl text-5xl font-bold leading-[.95] tracking-tight sm:text-8xl">Tus oportunidades son visibles.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#packs" className="button-primary">Elegir oportunidades</a><a className="button-secondary border-white/30 bg-blue-700" href={`https://wa.me/?text=${encodeURIComponent("Mira este sorteo transparente: "+(process.env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000"))}`} target="_blank" rel="noreferrer">Compartir por WhatsApp</a></div></div></section></main>
 <footer className="border-t border-white/10 py-10"><div className="shell flex flex-col gap-5 text-sm text-slate-400 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 {BRAND.provisionalName}. Proyecto en validación.</p><div className="flex gap-5"><a href="/bases">Bases legales</a><a href="/privacidad">Privacidad</a><a href="/admin">Administración</a></div></div></footer>
 <PurchaseFlow key={selected??"closed"} raffleId={raffle.id} total={raffle.totalSlots} selected={selected} onClose={()=>setSelected(null)}/></>;
}
function Stat({label,value,lime=false}:{label:string;value:string;lime?:boolean}){return <div className="card rounded-2xl p-6"><span className="muted text-xs">{label}</span><b className={`display mt-3 block text-3xl ${lime?"text-[#b8ff3d]":""}`}>{value}</b></div>}
function Info({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-dashed border-white/15 p-6"><b className="display">{title}</b><p className="muted mt-2 text-sm leading-6">{children}</p></div>}
